# Generated by Django 5.1.3 on 2024-11-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0002_alter_product_image'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('customer', 'product'), name='name of constraint'),
        ),
    ]
