services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: wait-for-it postgres:5432 -- ./entrypoint.sh
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - .:/app
  postgres:
    image: postgres:13.4-buster
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres: