# Generated by Django 5.1.3 on 2024-11-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('brand', models.CharField(max_length=128, verbose_name='brand')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('reviewScore', models.FloatField(blank=True, null=True, verbose_name='review score')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
